language: go
go:
- '1.7'
services:
- docker
env:
  global:
  - REPO=koudaiii/demo
  - K8S_VERSION=v1.4.5
  - BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
  - TAG=$BRANCH-${TRAVIS_COMMIT::8}
  # travis encrypt DOCKER_EMAIL=email
  - secure: zAm2sw4cy9JVlI4aXGG/8hVV8e6ySpMXoN7/Q1A10u7X3C1CUj3cZkpGlhrf+38lPRVEpP0I6uqLvFU9Dpab2MFQcaoUX42dRiz5LoAoDq9J0Xddanwb/MANCIa391mP6FER1MFDzwsQ1+mEesoK3ng4uhuKOkDQEV4F11vbRlBff6kcdOjrOZHGLVrLW+TAAyJ8dASJ6hgXWbpVswspwmZfQvMR052de72GPZlN8dyQvYAtrLmHiLRLdv23Ax0BSF6QwxPM6o85L5Hu8uSu7FYYFuSZefOA75M9cPZRph69vr5DLyYC0hdGuu4Witb3/jgENBDnEFUI7pHNVydeBDkw1NCTf+HUnAXojDs+LsfmnbXpEn5FzaxjqFE2RO+mZYWHTdXdhkDGjzsEfUmZkzpE/SA0zwA8WnuSNqXF6UC86oaIQTMrUsbL04HipJZcoicLo5fYRZJ03LAB5YmW0R5DMxl8XN07fpwTkmbNDam+kVZ3iFkoDKVEoRQlcPT9OhOPE7CZA0CVcVPgheYrlII8L8k/+Ou1JthpiOzmFCSPRpMku+GeN9ucQERtTMGOVkLut1sAMvepcfWVPYkliu+/1NeAh4vFQE19+mvoHUNQEFVuTQm2FIOVPYKVMSNkpCJJD2TaHKV3BW5BSH8/Axg+khGEbcmsCGPuKskQTzw=
  # travis encrypt DOCKER_USERNAME=name
  - secure: PCii6K0Vn1GZM9IsbeiqRVlFjTWQFET0tSQajPcj59rBgHYCvMXuK3Qk1NCKhQCFwkVhbNlOnsmpKtCDQAqsGgibCz8A8L8JUaUqnXafOtxTB/etC5z7IEC4RhFmqtVvRk7DT4aAApQnmCiLnlaALbJgF3ySyj/1DM6HRAC9gGIa3mm0AzG8nSDopyJ61hKDOjHr5wc18oe0kIPA0rvyP2r6SxY7jRxy8JDsDcFPQg07PoByzZKtLK6xCeFBecWgHAL+hCARYvmsAMo956GvooHZiruwc87UOUTmZW//f//+B79mxnQroiIMHmzO4gEv7IWTOG8kw3375lIhtJSkVN5eGqh3N69RqDjR48ogEbzXWfaYufV6q6WAUjZRAUca+YeSVmxZpahenaG/i6psPwi/XSOHbY8WzSR9ZNQwi7Um67KbCtBOm0ts0m03q1VWgqFWP4qBtSFxaYV5kZ8NsXKAOxD9G5Y3Y90qzGhSWqNqz53HWpIcv+gTRXvfvVGd9j+Ff6CMP1XnYB0s8IF1QJi3zk5pDbmsG4O1jIRlQo0/RKQCcr/JogjmNOLfm5Ol5hzLESJEhQsuPphvu45M+Z6vtg4/jCk4OlKsJO0uNN/A309yUE5IThf7flkFB+Ho9o2IkHUGlGHokjXqFnqPh+i0UzIbiweG6AUcyLmpJ4k=
  # travis encrypt DOCKER_PASSWORD=password
  - secure: uqBL7KUfy+yaZ15HGf5o7O455G+KDecs/JMv+xW+U8M5OQ6dGNXFa63P2MPFA/qOrgkbwBPGd4zLq7gSKFf0uQMvWg4lJatoLfyWZbL735ggIAFcufnHI+FfWjo917z/q9XtVvA9bGHUBvqqGI6QTLC1Qu+05nOOUyJqSrgCYa3HBhSqC0auIJtIAuk169XOkAuH/I5Z9RBp313B1Ii4Ln4MNarcWjFTOS7tv2Fe5wRvgyp59mxM9EKJvM+5HSq3RAWlHYLCy2N5pp77R2jj+5ZZfpPrtCpqLO/ZE3Dnr1CkOJyWfMCMlemkG62YSMuu+qydst3gfWpmj3OjYJ51thVcS/DYHH0JjaEZj0Xv17Mb+8TMfRn2E9YKS+VSRju9rTRh5WH0LapHMw4u+S44zrcrMSzlB9T8EwVFHFRzxpmsrQAR9dRq2R4VUmmgeUz0ipodMIeOaSC0wQ366+FkBv1rhKl0mgTFhj9wZ20pjIAlEW7VCj5HDdh6G31nN2zNfP4dUNsQnqyq76CHmznNFuMxKP+w0JBruGj5Ibdwcm66DSbetq6qb4dWUzUJka3/6HjxD6fhGnOnN60wJBsjWN+TCs0VwgOm95Gc07wDNZ7f7CLCggICn0N7nlz6/2TH6rDbQoBBIJUULyXEUUHb9m2xym18MRdYH013ztizeMo=

install:
  - curl -o ./kubectl "https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl"
  - chmod +x ./kubectl

script:
- echo ${TRAVIS_COMMIT::8}
- script/ci-build
