apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    name: demo
    role: web
spec:
  ports:
  - port: 80 # Service opened port.
    protocol: TCP
    targetPort: 8080 # Endpoint of containerPort
  selector:
    name: demo
    role: web
  type: LoadBalancer
